version: '3.2'
services:
  web:
    build: ./php-server
    container_name: innstant4
    environment:
    - APACHE_RUN_USER=www-data
    volumes:
    - type: bind
      source: ./src/innstant4
      target: /var/www/innstant4/
    - type: bind
      source: ./config/sites-enabled/innstant.me.conf
      target: /etc/apache2/sites-enabled/innstant.me.conf
    - type: bind
      source: ./config/php/php.ini-development
      target: /etc/php/7.0/apache2/php.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/apache2/conf.d/20-xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/apache2/conf.d/20-yaml.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/cli/conf.d/20-xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/cli/conf.d/20-yaml.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/mods-available/xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/mods-available/yaml.ini
    - type: bind
      source: ./logs/apache-logs
      target: /var/log/apache2
    ports:
    - 80:80
    networks:
      frontend:
        ipv4_address: 172.16.238.15
    working_dir: /var/www/innstant4
    extra_hosts:
    - innstant.me:127.0.0.1
    - aether3.me:172.16.238.10
    external_links:
      - aether3:aether3

  composer:
    build: ./composer
    container_name: composer-i
    volumes:
    - type: bind
      source: ./src/innstant4
      target: /var/www/innstant4/
    working_dir: /var/www/innstant4
    command: bash -c "composer install"

  node:
    image: node:8-slim
    container_name: node-i
    depends_on:
    - composer
    volumes:
    - type: bind
      source: ./src/innstant4
      target: /var/www/innstant4/
    working_dir: /var/www/innstant4/
    command: bash -c "npm install && npm run watch"

networks:
  frontend:
    external:
      name : docker-aether3_backend
